### ISSUE TITLE
SVGR imports don't work

### ISSUE THREAD

**Issue by valtism** [zenclabs/reactpreview#6]
Heya François! Thanks for the beta invite 😃 

```
SyntaxError: The requested module '/preview/src/images/enter.svg?import' does not provide an export named 'ReactComponent'
```

I am using [`vite-plugin-svgr`](https://github.com/pd4d10/vite-plugin-svgr) to import svg images as react components like `import { ReactComponent as EnterIcon } from "../images/enter.svg"`

Unsure if this is also an issue in `create-react-app` which uses SVGR by default under the hood.

**Comment by valtism** [comment]
Also, I am unable to copy from the console. Would be nicer to copy the errors instead of having to type them out 😅

**Comment by fwouts** [comment]
Thank you for filing the issue!

In fact SVGR support is already there but only enabled if you have the `svg-react-loader` package installed. Therefore it should be an easy fix! In the meantime you can probably fix it by creating a dummy directory: `mkdir node_modules/svgr-react-loader`

I'll add `vite-plugin-svgr` as an alternative, along with an option to override the default behaviour in `reactpreview.config.js`.

Stay tuned for the update and please keep sending feedback! 😄

**Comment by fwouts** [comment]
Hey @valtism, this should now be solved in v0.1.1. You should see an "Update available" banner pop up the next time you open React Preview.

Would you be able to test it out? In your case it should work automagically (let me know if it doesn't), but you can also specify `svgr: true` in `reactpreview.config.js` to force the behaviour.

The copy-paste issue should be solved too (tested on Mac & Windows).

**Comment by fwouts** [comment]
@valtism Have you had a chance to try out the update? :)

**Comment by valtism** [comment]
Heya, sorry been busy so haven't yet. I had to disable the extension because the extension spawned a worker thread or something that was chewing CPU, and it didn't stop when the extension was disabled. 

So I still get this issue in v0.1.1:
```
SyntaxError: The requested module '/preview/src/images/close.svg?import' does not provide an export named 'ReactComponent'
```

I don't know if you tested it exactly with the `vite-plugin-svgr` package, because that's the one I'm using. My imports look like this: `import { ReactComponent as CloseIcon } from "../images/close.svg"`

**Comment by fwouts** [comment]
Thank you for the very helpful feedback @valtism.

I had assumed that `vite-plugin-svgr` had the same behaviour as `react-svg-loader`, when in fact one exposes a default export while the other exposes a named export. This is why it still didn't work. I've added tests to make sure this won't ever break again.

There are also a ton of performance improvements, you shouldn't see React Preview hogging your CPU in the next version anymore. Hoping to make a new release with these changes in the next couple of days :)

**Comment by fwouts** [comment]
Hey @valtism, I've just released v0.2.0, keen to hear your thoughts on it! The default behaviour should now be what you expect for SVGR support. Keen to hear if you still notice CPU usage as well :)

**Comment by valtism** [comment]
SVGR imports seem to work! Unfortunately, all other styles don't seem to be loading. I'll open a new issue for that.
